controller_list:
  - name: fake_dual_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - l_ur5_arm_shoulder_pan_joint
      - l_ur5_arm_shoulder_lift_joint
      - l_ur5_arm_elbow_joint
      - l_ur5_arm_wrist_1_joint
      - l_ur5_arm_wrist_2_joint
      - r_ur5_arm_shoulder_pan_joint
      - r_ur5_arm_shoulder_lift_joint
      - r_ur5_arm_elbow_joint
      - r_ur5_arm_wrist_1_joint
      - r_ur5_arm_wrist_2_joint
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - l_ur5_arm_shoulder_pan_joint
      - l_ur5_arm_shoulder_lift_joint
      - l_ur5_arm_elbow_joint
      - l_ur5_arm_wrist_1_joint
      - l_ur5_arm_wrist_2_joint
      - l_ur5_arm_wrist_3_joint
      - l_palm_finger_1_joint
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - r_ur5_arm_shoulder_pan_joint
      - r_ur5_arm_shoulder_lift_joint
      - r_ur5_arm_elbow_joint
      - r_ur5_arm_wrist_1_joint
      - r_ur5_arm_wrist_2_joint
      - r_ur5_arm_wrist_3_joint
      - r_palm_finger_1_joint
  - name: fake_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - l_palm_finger_1_joint
      - l_finger_1_joint_1
      - l_finger_1_joint_2
      - l_finger_1_joint_3
      - l_palm_finger_2_joint
      - l_finger_2_joint_1
      - l_finger_2_joint_2
      - l_finger_2_joint_3
      - l_palm_finger_middle_joint
      - l_finger_middle_joint_1
      - l_finger_middle_joint_2
      - l_finger_middle_joint_3
  - name: fake_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - r_palm_finger_1_joint
      - r_finger_1_joint_1
      - r_finger_1_joint_2
      - r_finger_1_joint_3
      - r_palm_finger_2_joint
      - r_finger_2_joint_1
      - r_finger_2_joint_2
      - r_finger_2_joint_3
      - r_palm_finger_middle_joint
      - r_finger_middle_joint_1
      - r_finger_middle_joint_2
      - r_finger_middle_joint_3
initial:  # Define initial robot poses per group
  - group: dual_arm
    pose: duan_arm_home